// examples/nextjs/app/_components/redirect/redirect.tsx
"use client";

import { useCallback, useEffect, useRef } from "react";
import { useSearchParams } from "next/navigation";
import { PlexyCheckout, PlexyCheckoutError, UIElement } from "@plexy/plexy-web";
import makeDetailsCall from "@/app/_utils/makeDetailsCall";
import type {
    AdditionalDetailsActions,
    AdditionalDetailsData,
    PaymentCompletedData,
    PaymentFailedData,
} from "@plexy/plexy-web";

export default function Redirect() {
    const isRedirectHandled = useRef<boolean>(false);
    const searchParams = useSearchParams();

    const handleRedirectResult = useCallback(
        async (redirectResult: string, sessionId: string) => {
            const isSessionsFlow = !!sessionId;

            const checkout = await PlexyCheckout({
                analytics: {
                    enabled: false,
                },
                clientKey: process.env.NEXT_PUBLIC_CLIENT_KEY,
                environment: "test",
                countryCode: "US",

                // If it is sessions flow, pass the sessionId back to the library
                ...(isSessionsFlow && {
                    session: {
                        id: sessionId,
                    },
                }),

                // If it is NOT sessions flow, add the 'onAdditionalDetails' so you can handle the /payment/details part here
                ...(!isSessionsFlow && {
                    onAdditionalDetails: async (
                        state: AdditionalDetailsData,
                        component: UIElement,
                        actions: AdditionalDetailsActions,
                    ) => {
                        try {
                            const { resultCode } = await makeDetailsCall(
                                state.data,
                            );
                            actions.resolve({ resultCode });
                        } catch (error) {
                            console.error(error);
                            actions.reject();
                        }
                    },
                }),

                onPaymentCompleted(
                    data: PaymentCompletedData,
                    component?: UIElement,
                ) {
                    document.querySelector(
                        "#result-container > pre",
                    ).innerHTML = JSON.stringify(data, null, "\t");
                },
                onPaymentFailed(
                    data?: PaymentFailedData,
                    component?: UIElement,
                ) {
                    document.querySelector(
                        "#result-container > pre",
                    ).innerHTML = "Payment failed";
                },
                onError: (error: PlexyCheckoutError) => {
                    console.error("Something went wrong", error);
                },
            });

            checkout.submitDetails({ details: { redirectResult } });
        },
        [],
    );

    useEffect(() => {
        const redirectResult = searchParams.get("redirectResult");
        const sessionId = searchParams.get("sessionId");

        if (redirectResult) {
            if (isRedirectHandled.current) return;

            isRedirectHandled.current = true;
            void handleRedirectResult(redirectResult, sessionId);
        } else {
            document.querySelector("#result-container").innerHTML =
                "No redirectResult available";
        }
    }, [searchParams, handleRedirectResult]);

    return (
        <div id="result-container">
            <pre>Loading...</pre>
        </div>
    );
}

// examples/angular/src/components/redirect/redirect.component.ts
import { Component, OnInit, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import {
    PlexyCheckout,
    PlexyCheckoutError,
    PaymentCompletedData,
    UIElement,
    PaymentFailedData,
    AdditionalDetailsData,
    AdditionalDetailsActions
} from '@plexy/plexy-web';
import { environment } from '../../environments/environment';
import { AdvancedFlowApiService } from '../../services/AdvancedFlowApi.service';

@Component({
    selector: 'plexy-sessions',
    standalone: true,
    templateUrl: './redirect.component.html'
})
export class RedirectPage implements OnInit {
    response: any;

    constructor(
        private apiService: AdvancedFlowApiService,
        @Inject(PLATFORM_ID) private platformId: Object
    ) {}

    ngOnInit(): void {
        if (isPlatformBrowser(this.platformId)) {
            this.handleRedirectResult();
        }
    }

    async handleRedirectResult() {
        const urlParams = new URLSearchParams(window.location.search);
        const redirectResult = urlParams.get('redirectResult');
        const sessionId = urlParams.get('sessionId');

        if (!redirectResult) {
            this.response = 'No redirectResult available';
            return;
        }

        const isSessionsFlow = !!sessionId;

        const checkout = await PlexyCheckout({
            analytics: {
                enabled: false
            },
            clientKey: environment.clientKey,
            environment: 'test',
            countryCode: 'US',

            // If it is sessions flow, pass the sessionId back to the library
            ...(isSessionsFlow && {
                session: {
                    id: sessionId
                }
            }),

            // If it is NOT sessions flow, add the 'onAdditionalDetails' so you can handle the /payment/details part here
            ...(!isSessionsFlow && {
                onAdditionalDetails: async (state: AdditionalDetailsData, component: UIElement, actions: AdditionalDetailsActions) => {
                    this.apiService.makeDetailsCall(state.data).subscribe(result => {
                        if (!result.resultCode) {
                            actions.reject();
                            return;
                        }

                        const { resultCode, action, order, donationToken } = result;

                        actions.resolve({
                            resultCode,
                            action,
                            order,
                            donationToken
                        });
                    });
                }
            }),

            onPaymentCompleted: (data: PaymentCompletedData, component?: UIElement) => {
                this.response = JSON.stringify(data, null, '\t');
            },
            onPaymentFailed: (data?: PaymentFailedData, component?: UIElement) => {
                this.response = 'Payment failed';
            },
            onError: (error: PlexyCheckoutError) => {
                this.response = 'Something went wrong';
                console.error(error);
            }
        });

        checkout.submitDetails({ details: { redirectResult } });
    }
}
