// examples/angular/src/components/redirect/redirect.component.ts
import { Component, OnInit, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import {
    PlexyCheckout,
    PlexyCheckoutError,
    PaymentCompletedData,
    UIElement,
    PaymentFailedData,
    AdditionalDetailsData,
    AdditionalDetailsActions
} from '@plexy/plexy-web';
import { environment } from '../../environments/environment';
import { AdvancedFlowApiService } from '../../services/AdvancedFlowApi.service';

@Component({
    selector: 'plexy-sessions',
    standalone: true,
    templateUrl: './redirect.component.html'
})
export class RedirectPage implements OnInit {
    response: any;

    constructor(
        private apiService: AdvancedFlowApiService,
        @Inject(PLATFORM_ID) private platformId: Object
    ) {}

    ngOnInit(): void {
        if (isPlatformBrowser(this.platformId)) {
            this.handleRedirectResult();
        }
    }

    async handleRedirectResult() {
        const urlParams = new URLSearchParams(window.location.search);
        const redirectResult = urlParams.get('redirectResult');
        const sessionId = urlParams.get('sessionId');

        if (!redirectResult) {
            this.response = 'No redirectResult available';
            return;
        }

        const isSessionsFlow = !!sessionId;

        const checkout = await PlexyCheckout({
            analytics: {
                enabled: false
            },
            clientKey: environment.clientKey,
            environment: 'test',
            countryCode: 'US',

            // If it is sessions flow, pass the sessionId back to the library
            ...(isSessionsFlow && {
                session: {
                    id: sessionId
                }
            }),

            // If it is NOT sessions flow, add the 'onAdditionalDetails' so you can handle the /payment/details part here
            ...(!isSessionsFlow && {
                onAdditionalDetails: async (state: AdditionalDetailsData, component: UIElement, actions: AdditionalDetailsActions) => {
                    this.apiService.makeDetailsCall(state.data).subscribe(result => {
                        if (!result.resultCode) {
                            actions.reject();
                            return;
                        }

                        const { resultCode, action, order, donationToken } = result;

                        actions.resolve({
                            resultCode,
                            action,
                            order,
                            donationToken
                        });
                    });
                }
            }),

            onPaymentCompleted: (data: PaymentCompletedData, component?: UIElement) => {
                this.response = JSON.stringify(data, null, '\t');
            },
            onPaymentFailed: (data?: PaymentFailedData, component?: UIElement) => {
                this.response = 'Payment failed';
            },
            onError: (error: PlexyCheckoutError) => {
                this.response = 'Something went wrong';
                console.error(error);
            }
        });

        checkout.submitDetails({ details: { redirectResult } });
    }
}

// examples/nuxt/pages/redirect.vue
<script lang="ts">
import { DEFAULT_COUNTRY } from '~/constants';
import { PlexyCheckout } from '@plexy/plexy-web/auto';
import type {
    AdditionalDetailsActions,
    AdditionalDetailsData,
    PlexyCheckoutError,
    PaymentCompletedData,
    PaymentFailedData,
    UIElement
} from '@plexy/plexy-web/auto';
import '@plexy/plexy-web/styles/plexy.css';


export default {
    data() {
        return {
            response: 'Loading...',
        };
    },

    async mounted() {
        this.handleRedirectResult();
    },

    methods: {
        async handleRedirectResult() {
            const urlParams = new URLSearchParams(window.location.search);
            const redirectResult = urlParams.get('redirectResult');
            const sessionId = urlParams.get('sessionId');
            const runtimeConfig = useRuntimeConfig();


            if (!redirectResult) {
                this.response = 'No redirectResult available';
                return;
            }

            const isSessionsFlow = !!sessionId;

            const checkout = await PlexyCheckout({
                analytics: {
                    enabled: false
                },
                clientKey: runtimeConfig.public.clientKey,
                environment: 'test',
                countryCode: DEFAULT_COUNTRY,

                // If it is sessions flow, pass the sessionId back to the library
                ...(isSessionsFlow && {
                    session: {
                        id: sessionId
                    }
                }),

                // If it is NOT sessions flow, add the 'onAdditionalDetails' so you can handle the /payment/details part here
                ...(!isSessionsFlow && {
                    onAdditionalDetails: async (state: AdditionalDetailsData, component: UIElement, actions: AdditionalDetailsActions) => {
                        try {
                            const result = await makeDetailsCall(state.data);

                            if (!result.resultCode) {
                                actions.reject();
                                return;
                            }

                            const { resultCode, action, order, donationToken } = result;

                            actions.resolve({
                                resultCode,
                                action,
                                order,
                                donationToken
                            });
                        } catch (error) {
                            console.error('onSubmit', error);
                            actions.reject();
                        }
                    }
                }),

                onPaymentCompleted: (data: PaymentCompletedData, component?: UIElement) => {
                    this.response = JSON.stringify(data, null, '\t');
                },
                onPaymentFailed: (data?: PaymentFailedData, component?: UIElement) => {
                    this.response = 'Payment failed';
                },
                onError: (error: PlexyCheckoutError) => {
                    this.response = 'Something went wrong';
                    console.error(error);
                }
            });

            checkout.submitDetails({ details: { redirectResult } });
        }
    }
};
</script>

<template>

    <Head>
        <Title>@plexy/plexy-web + Nuxt3</Title>
    </Head>
    <div class="redirect-result-page">
        <h1>Redirect response</h1>
        <pre class="result">{{ response }}</pre>
    </div>
</template>

<style scoped>
.redirect-result-page {
    display: flex;
    flex-direction: column;
    padding: 24px;
    gap: 20px;
    align-items: center;
    background-color: white;
    border-radius: 8px;
}

.result {
    width: 500px;
    white-space: pre-wrap;
    word-wrap: break-word;
}
</style>
