// examples/nextjs/app/_components/advanced-flow/advanced-flow.tsx
"use client";

import { useCallback, useEffect, useRef } from "react";
import { useSearchParams } from "next/navigation";
import {
    PlexyCheckout,
    Dropin,
    Card,
    CashAppPay,
    GooglePay,
    PayPal,
    PlexyCheckoutError,
    UIElement,
} from "@plexy/plexy-web/auto";
import "@plexy/plexy-web/styles/plexy.css";
import type {
    CoreConfiguration,
    DropinConfiguration,
    SubmitData,
    SubmitActions,
    AdditionalDetailsData,
    AdditionalDetailsActions,
    PaymentCompletedData,
    PaymentFailedData,
} from "@plexy/plexy-web";
import {
    DEFAULT_AMOUNT,
    DEFAULT_COUNTRY,
    DEFAULT_LOCALE,
} from "@/app/_utils/constants";
import makePaymentsCall from "@/app/_utils/makePaymentsCall";
import makePaymentMethodsCall from "@/app/_utils/makePaymentMethodsCall";
import makeDetailsCall from "@/app/_utils/makeDetailsCall";
import { parseAmount } from "@/app/_utils/amount-utils";

export default function AdvancedFlow() {
    const dropinRef = useRef<HTMLDivElement>(null);
    const isPlexyWebInitialized = useRef<boolean>(false);
    const searchParams = useSearchParams();

    const loadPlexy = useCallback(async () => {
        const countryCode = searchParams.get("countryCode") || DEFAULT_COUNTRY;
        const locale = searchParams.get("shopperLocale") || DEFAULT_LOCALE;
        const amount = parseAmount(
            searchParams.get("amount") || DEFAULT_AMOUNT,
            countryCode,
        );

        const paymentMethodsResponse = await makePaymentMethodsCall({
            countryCode,
            amount,
            shopperLocale: locale,
        });

        const options: CoreConfiguration = {
            clientKey: process.env.NEXT_PUBLIC_CLIENT_KEY,
            countryCode,
            amount,
            locale,
            environment: "test",
            analytics: {
                enabled: false,
            },
            paymentMethodsResponse,

            onSubmit: async (
                state: SubmitData,
                component: UIElement,
                actions: SubmitActions,
            ) => {
                try {
                    const result = await makePaymentsCall(
                        state.data,
                        countryCode,
                        locale,
                        amount,
                    );

                    if (!result.resultCode) {
                        actions.reject();
                        return;
                    }

                    const { resultCode, action, order, donationToken } = result;

                    actions.resolve({
                        resultCode,
                        action,
                        order,
                        donationToken,
                    });
                } catch (error) {
                    console.error("onSubmit", error);
                    actions.reject();
                }
            },

            onAdditionalDetails: async (
                state: AdditionalDetailsData,
                component: UIElement,
                actions: AdditionalDetailsActions,
            ) => {
                try {
                    const result = await makeDetailsCall(state.data);

                    if (!result.resultCode) {
                        actions.reject();
                        return;
                    }

                    const { resultCode, action, order, donationToken } = result;

                    actions.resolve({
                        resultCode,
                        action,
                        order,
                        donationToken,
                    });
                } catch (error) {
                    console.error("onSubmit", error);
                    actions.reject();
                }
            },

            onError(error: PlexyCheckoutError) {
                console.error("Something went wrong", error);
            },

            onPaymentCompleted(data: PaymentCompletedData, element: UIElement) {
                console.log(data, element);
            },

            onPaymentFailed(data: PaymentFailedData, element: UIElement) {
                console.log(data, element);
            },
        };

        const checkout = await PlexyCheckout(options);

        const dropinConfiguration: DropinConfiguration = {
            paymentMethodsConfiguration: {
                card: {
                    _disableClickToPay: true,
                },
            },
            paymentMethodComponents: [Card, PayPal, CashAppPay, GooglePay],
        };

        if (dropinRef.current) {
            new Dropin(checkout, dropinConfiguration).mount(dropinRef.current);
        }
    }, [searchParams]);

    useEffect(() => {
        if (!isPlexyWebInitialized.current) {
            isPlexyWebInitialized.current = true;
            void loadPlexy();
        }
    }, [loadPlexy]);

    return <div ref={dropinRef} id="dropin"></div>;
}

// examples/nuxt/components/AdvancedFlow.vue
<script lang="ts">
import { DEFAULT_AMOUNT } from '~/constants';
import { PlexyCheckout, Dropin } from '@plexy/plexy-web/auto';
import type { PlexyCheckoutError, UIElement, AdditionalDetailsActions, AdditionalDetailsData, CoreConfiguration, PaymentCompletedData, PaymentFailedData } from '@plexy/plexy-web/auto';
import '@plexy/plexy-web/styles/plexy.css';

export default {
    data() {
        return {
            dropin: null as Dropin | null,
        };
    },

    async mounted() {
        this.createCheckout();
    },

    methods: {
        async createCheckout() {
            const urlParams = new URLSearchParams(window.location.search);
            const countryCode = urlParams.get('countryCode') || 'US';
            const locale = urlParams.get('shopperLocale') || 'en-US';
            const amount = parseAmount(urlParams.get('amount') || DEFAULT_AMOUNT, countryCode);

            const runtimeConfig = useRuntimeConfig();
            const paymentMethodsResponse = await fetchPaymentMethods(countryCode, locale, amount);

            const options: CoreConfiguration = {
                paymentMethodsResponse,
                amount,
                countryCode,
                locale,
                environment: 'test',
                clientKey: runtimeConfig.public.clientKey,
                onSubmit: async (state, component, actions) => {
                    try {
                        const result = await makePaymentsCall(state.data, countryCode, locale, amount);

                        if (!result.resultCode) {
                            actions.reject();
                            return;
                        }

                        const { resultCode, action, order, donationToken } = result;

                        actions.resolve({
                            resultCode,
                            action,
                            order,
                            donationToken
                        });
                    } catch (error) {
                        console.error('onSubmit', error);
                        actions.reject();
                    }
                },
                onAdditionalDetails: async (state: AdditionalDetailsData, component: UIElement, actions: AdditionalDetailsActions) => {
                    try {
                        const result = await makeDetailsCall(state.data);

                        if (!result.resultCode) {
                            actions.reject();
                            return;
                        }

                        const { resultCode, action, order, donationToken } = result;

                        actions.resolve({
                            resultCode,
                            action,
                            order,
                            donationToken
                        });
                    } catch (error) {
                        console.error('onSubmit', error);
                        actions.reject();
                    }
                },
                onPaymentCompleted(data: PaymentCompletedData, element?: UIElement) {
                    console.log('onPaymentCompleted', data, element);
                },
                onPaymentFailed(data: PaymentFailedData, element?: UIElement) {
                    console.log('onPaymentFailed', data, element);
                },
                onError(error: PlexyCheckoutError) {
                    console.error('Something went wrong', error);
                },
            };

            const checkout = await PlexyCheckout(options);

            this.dropin = new Dropin(checkout, {
                paymentMethodsConfiguration: {
                    card: {
                        _disableClickToPay: true
                    }
                }
            });
            this.dropin.mount(this.$refs.dropinRef as HTMLElement);
        }
    }
};
</script>

<template>
    <div>
        <div class="payment" ref="dropinRef"></div>
    </div>
</template>

<style scoped>
.payment {
    margin: auto;
    max-width: 800px;
}
</style>
